day = int(input("enter your birth day"))
month = int(input("enter your birth month"))
year = int(input("enter your birth year"))
print(day,"/",month,"/",year)
day2 = int(input("enter today's day"))
month2 = int(input("enter the month"))
year2 = int(input("enter the year"))
today = (day2,"/",month2,"/",year2)
birthday = (day,"/",month,"/",year)
print(today - birthday)